# Generated by Django 5.0.6 on 2024-07-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, default='profile_photo/default_profile.jpg', null=True, upload_to='profile_photo', verbose_name='프로필'),
        ),
    ]
