# Generated by Django 5.0.6 on 2024-07-05 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='팀 이름')),
                ('description', models.TextField(blank=True, verbose_name='팀 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='팀 생성일')),
                ('photo', models.ImageField(blank=True, default='team_photo/default_photo.jpg', null=True, upload_to='team_photo', verbose_name='팀이미지')),
                ('creater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('like_users', models.ManyToManyField(related_name='like_teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='할일 제목')),
                ('finished', models.BooleanField(default=False)),
                ('manager', models.ManyToManyField(default=True, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
