# Generated by Django 5.0.6 on 2024-07-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_created_at_team_creater_alter_team_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_photo', verbose_name='팀이미지'),
        ),
    ]
