# Generated by Django 5.0.6 on 2024-07-03 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_alter_team_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='like_users',
            field=models.ManyToManyField(related_name='like_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
